FROM node:18

WORKDIR /app

RUN apt-get update && apt-get install -y python3 python3-pip python3-venv make g++ && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv


COPY package*.json ./
RUN npm install

COPY processing/requirements.txt ./processing/requirements.txt
RUN /venv/bin/pip install --upgrade pip && /venv/bin/pip install -r processing/requirements.txt

COPY . .

ENV PATH="/venv/bin:$PATH"

EXPOSE 5000

CMD ["npm", "run", "dev"]
